import { Router } from 'express';
import { auth } from '../middlewares/auth.js';
import { listEmployees, getEmployee, createEmployee, updateEmployee, deleteEmployee } from '../controllers/employeeController.js';
const router = Router();
router.use(auth);
router.get('/', listEmployees);
router.get('/:id', getEmployee);
router.post('/', createEmployee);
router.put('/:id', updateEmployee);
router.delete('/:id', deleteEmployee);
export default router;
